services:
  api:
    container_name: webapi
    build:
      context: ./Adres.Procurement.Services/
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
      - migrator
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DB_CONNECTION_STRING: "Server=sqlserver,1433;Database=ProcurementsDb;User Id=sa;Password=Your_strong_password_123;TrustServerCertificate=True;"
    ports:
      - "8080:8080"
    networks:
      - appnet

  migrator:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    container_name: migrator
    working_dir: /src
    volumes:
      - ./Adres.Procurement.Services:/src
    environment:
      DB_CONNECTION_STRING: "Server=sqlserver,1433;Database=ProcurementsDb;User Id=sa;Password=Your_strong_password_123;TrustServerCertificate=True;"
      PATH: "/root/.dotnet/tools:$PATH"
    entrypoint: ["/bin/sh", "-c", "dotnet restore && dotnet tool install --global dotnet-ef && dotnet ef database update --startup-project Adres.Procurement.Api --project Adres.Procurement.Infrastructure"]
    depends_on:
      - sqlserver
    networks:
      - appnet

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      SA_PASSWORD: "Your_strong_password_123"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - appnet

  web:
    container_name: angularweb
    build:
      context: ./Adres.Web/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - appnet

networks:
  appnet:

volumes:
  sql_data:
